# Generated by Django 4.2.30 on 2026-06-28 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('geojson_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['official_name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('scrape_interval_hours', models.PositiveIntegerField(default=3)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=50)),
                ('last_scrape_log', models.TextField(blank=True)),
                ('selector_config', models.JSONField(default=dict)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_source', to='django_celery_beat.periodictask')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('unresolved_location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic_lecture', 'Academic / Lecture'), ('social_party', 'Social / Party'), ('free_food', 'Free Food'), ('sports_athletics', 'Sports / Athletics'), ('arts_performance', 'Arts / Performance'), ('career_professional', 'Career / Professional'), ('club_org_meeting', 'Club / Org Meeting'), ('religious_spiritual', 'Religious / Spiritual'), ('volunteer_community', 'Volunteer / Community'), ('health_wellness', 'Health / Wellness')], max_length=50)),
                ('other_info', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('missed_scrape_count', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.building')),
                ('scrape_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.scrapesource')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='BuildingAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('scraper', 'Scraper'), ('admin', 'Admin'), ('student_report', 'Student Report')], default='scraper', max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.building')),
            ],
            options={
                'verbose_name_plural': 'building aliases',
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('event_name', 'building', 'start_time'), name='unique_event_dedup'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingalias',
            unique_together={('building', 'alias')},
        ),
    ]
