# Generated by Django 5.2.16 on 2026-07-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapesource',
            name='source_type',
            field=models.CharField(choices=[('html', 'HTML page'), ('email', 'Email inbox')], default='html', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
