# Generated by Django 4.2.30 on 2026-09-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_admin_notified_at_event_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('android_apk', models.FileField(blank=True, upload_to='downloads/')),
                ('ios_ipa', models.FileField(blank=True, upload_to='downloads/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
