# Generated by Django 5.2.16 on 2026-07-15 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_scrapesource_source_type_alter_scrapesource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=998)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('events_extracted', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('scrape_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='core.scrapesource')),
            ],
            options={
                'ordering': ['-processed_at'],
                'unique_together': {('scrape_source', 'message_id')},
            },
        ),
    ]
